troika-online-default-rtdb:
  people:
    email: email
    username: name
  skills:
    person**:
      [skills]
    character*:
      [skills]
    library:
      [skills]
  possessions:
    person**:
      [items]
    character*:
      [items]
    library:
      [items]
  spells:
    person**:
      [Spells]
    character*:
      [Spells]
    library:
      [Spells]
  actions:
    game*:
      [Actions]
  characters:
    person**:
      [Characters]
    game*:
      [Characters]
    library:
      [Characters]
  games:
    [Games]
  tags:
    [Tags]

---

Skills:
  skillId*:
    name: string
    description: string
    tags: [tag*]

