export const blankCharacter = {
  background: '',
  game: '',
  isTemplate: false,
  luck_current: 0,
  luck_max: 0,
  monies: 0,
  name: '',
  owner: '',
  player: '',
  possessions: [],
  provisions: 0,
  skill: 0,
  skills: {},
  sort_name: '',
  special: '',
  stamina_current: 0,
  stamina_max: 0,
};
